name: Nikos Mitilineos
favicon: null
layout_spectrum: 0.75409
typography_spectrum: 0.2339045195840299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.8778786882758141
purpose: []
